import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rob Mayo | Software Engineer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

// src/app/RootLayout.jsx

// import React from "react";
// import "./globals.css";
// import Navbar from "./components/navbar"; // Adjust the import path as necessary

// const RootLayout = ({ children }) => {
//   return (
//     <>
//     <Navbar>
//       <main>{children}</main>
//     </Navbar>
//     </>
//   );
// };

// export default RootLayout;


